### PR TITLE
Add Voice input Method

### LINKED ISSUE #21: Implement voice intergration
User can tap on mic button and say something . That text can then be translated to some other language.

### PR DESCRIPTION
**Pull request by refactor-droidyy**
Fix #21

### CODE REVIEW

**Comment by refactor-droidyy** [comment]
@somenath1435  please review.

**Comment by ShivangiSingh17** [comment]
@refactor-droidyy can you please attach screenshots.

**Comment by refactor-droidyy** [comment]
Screenshot for the change

Screenshot_2019-12-25-00-53-23-770_io github njackwinterofcode translatex

**Comment by refactor-droidyy** [comment]
@ShivangiSingh17 please have a look.

**Comment by ShivangiSingh17** [comment]
@refactor-droidyy solve the conflicts.

**Comment by refactor-droidyy** [comment]
@ShivangiSingh17 merge conflict resolved.

**Pull request merged**
