### PR TITLE
UI changes done

### PR DESCRIPTION
**Pull request by Mehulipal**
feature improved #36

### CODE REVIEW

**Comment by ShivangiSingh17** [comment]
@Mehulipal attach all the screenshots of the same and resolve the conflicts.

**Comment by Mehulipal** [comment]
OK sure On 03-Jan-2020 11:43 PM, Shivangi Singh <notifications@github.com> wrote:@Mehulipal attach all the screenshots of the same and resolve the conflicts.

**Comment by Mehulipal** [comment]
But which conflicts exactly? On 04-Jan-2020 5:29 AM, mehuli_1901cb27@iitp.ac.in wrote:OK sure On 03-Jan-2020 11:43 PM, Shivangi Singh <notifications@github.com> wrote:@Mehulipal attach all the screenshots of the same and resolve the conflicts.

**Comment by ShivangiSingh17** [comment]
There is  app/src/main/res/values/strings.xml conflicting file and add screenshots of the new UI.

**Review by ShivangiSingh17 — CHANGES_REQUESTED** [review]
Resolve the conflicting file and attach screenshots please.

**Comment by Mehulipal** [comment]
Conflict resolved, please review

**Comment by Mehulipal** [comment]
# Screenshot of UI changes
image
image

**Pull request merged**
